modbus: !include own_files/modbus.yaml
climate: !include own_files/climates.yaml

#input number
input_number:
  proxon_luefterstufe_slider:
    name: Proxon L端fterstufe - Slider
    min: 1
    max: 4
    step: 1
    
  proxon_sollwert_wassertemperatur_slider:
    name: Proxon Sollwert Wassertemperatur - Slider
    min: 40
    max: 55
    step: 1

  proxon_sollwert_freigabe_heizstab_slider:
    name: Proxon Freigabetemperatur Heizstab - Slider
    min: 40
    max: 70
    step: 1
    
input_select:
  proxon_betriebsart_select:
    name: Proxon Betriebsart - Select
    options:
      - 'Aus'
      - 'Sommerbetrieb'
      - 'Winterbetrieb'
      - 'ECO Komfortbetrieb'
      - 'Ofenbetrieb'
    icon: mdi:heat-pump

  proxon_luefterstufe_select:
    name: Proxon L端fterstufe - Select
    options:
      - '1'
      - '2'
      - '3'
      - '4'
    icon: mdi:fan
    
template:
  - sensor:
    - name: 'Proxon Filter Tage'
      state: >
        {% set filter_raw = states('sensor.proxon_nutzzeit_fwt_geratefilter') | float %}
        {{ (((filter_raw) *2) /24) | round(0) }}
      unit_of_measurement: "Tage"
    - name: "Proxon Filter Resttage"
      state: >
        {% set filter_tage = states('sensor.proxon_filter_tage') | float %}
        {{ (180 - filter_tage) | round(0) }}
      unit_of_measurement: "Tage"

  - sensor:
      name: "Proxon aktueller Betrieb template"
      state: >-
        {% set d = {
        '0': 'L端ftungsbetrieb', '1': 'Heizbetrieb', 
        '2': 'K端hlbetrieb'} %}
        {% if states('sensor.proxon_aktueller_betrieb') in d.keys() %}
          {{ d.get(states('sensor.proxon_aktueller_betrieb')) }}
        {% else %}
          Unknown
        {% endif %}